name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.1.5
author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  dio: ^3.0.10
  rxdart: ^0.24.1

#Dummy classes
flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.alice
        pluginClass: Alice
      ios:
        pluginClass: Alice
